name: pelusica

permissions:
  contents: write

on:
  push:
    tags:
      - "*.*.*"
      - "test-pelusica-*"

jobs:
  Web:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: |
          set -x
          curl -L -o calm.tgz https://github.com/VitoVan/calm/releases/download/1.3.1/calm.tgz
          mkdir calm
          tar xvf calm.tgz
          ls -lah calm
          export PATH=$PATH:$(pwd)/calm/
          export APP_NAME=Pelusica
          export REBUILD_WASM_P=yes
          calm publish-web
          ls -lah .
          zip -r -9 ${APP_NAME}-web.zip ./web
          cp *.zip ../../../
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          draft: true
          files: |
            *-web.zip
  Linux:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: |
          set -x
          curl -L -o calm.tgz https://github.com/VitoVan/calm/releases/download/1.3.1/calm.tgz
          mkdir calm
          tar xvf calm.tgz
          ls -lah calm
          export PATH=$PATH:$(pwd)/calm/
          export APP_NAME=Pelusica
          calm publish
          ls -lah .
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          draft: true
          files: |
            *.AppImage
  macOS:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-12, macos-13, macos-14]

    env:
      CI_MATRIX_OS: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: |
          set -x
          export OS_SUBFIX=".${CI_MATRIX_OS}"
          curl -L -o calm.dmg https://github.com/VitoVan/calm/releases/download/1.3.1/calm${OS_SUBFIX}.dmg
          hdiutil attach calm.dmg
          cp -R "/Volumes/Calm - CALM/Calm.app/Contents/MacOS/" calm
          ls -lah calm
          rm calm.dmg
          export PATH=$PATH:$(pwd)/calm/
          export APP_VERSION=1.0.0
          export APP_ID=com.vitovan.pelusica
          export APP_NAME=Pelusica
          calm publish
          ls -lah .
          mv *.dmg Pelusica${OS_SUBFIX}.dmg
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          draft: true
          files: |
            *.dmg
  Windows:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3

      - uses: msys2/setup-msys2@v2

      - name: Build
        shell: msys2 {0}
        run: |
          set -x
          pacman -S --noconfirm --needed unzip
          curl -L -o calm.zip https://github.com/VitoVan/calm/releases/download/1.3.1/calm.zip
          unzip calm.zip
          ls -lah calm
          export PATH=$PATH:$(pwd)/calm/
          export APP_NAME=Pelusica
          calm publish
          mv ./*-Installer.exe ./Pelusica.exe
          ls -lah .
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          draft: true
          files: |
            *.exe
